# Generated by Django 2.0.2 on 2018-02-05 11:19

# Third Party Libraries
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Pseudo',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
            ],
        ),
    ]
